export const EXAMPLE_PROJECTS = [
  {
    framework: 'Svelte',
    title: 'Svelte kanban board',
    description: 'A Trello clone using Briven as the storage system.',
    url: 'https://github.com/joshnuss/briven-kanban',
    type: 'app',
  },
  {
    framework: 'nextjs',
    title: 'Next.js Realtime chat app',
    description: 'Next.js Slack clone app using Briven realtime subscriptions',
    url: 'https://github.com/briven/briven/tree/master/examples/slack-clone/nextjs-slack-clone',
    type: 'app',
  },
  {
    framework: 'nextjs',
    title: 'Next.js Subscription and Auth',
    description: 'The all-in-one starter kit for high-performance SaaS applications.',
    url: 'https://github.com/nextjs/saas-starter',
    type: 'app',
  },
  {
    framework: 'Expo',
    title: 'Expo Starter',
    description: 'Template bottom tabs with auth flow (Typescript)',
    url: 'https://github.com/codingki/react-native-expo-template/tree/master/template-typescript-bottom-tabs-briven-auth-flow',
    type: 'mobile',
  },
  {
    framework: 'NestJS',
    title: 'NestJS example',
    description: 'NestJS example using Briven Auth',
    url: 'https://github.com/hiro1107/nestjs-briven-auth',
    type: 'app',
  },
  {
    framework: 'React',
    title: 'React realtime chat app',
    description: 'Example app of real-time chat using briven realtime api',
    url: 'https://github.com/shwosner/realtime-chat-briven-react',
    type: 'app',
  },
  {
    framework: 'nextjs',
    title: 'Next.js todo list app',
    description: 'Next.js todo list example',
    url: 'https://github.com/briven/briven/tree/master/examples/todo-list/nextjs-todo-list',
    type: 'app',
  },
  {
    framework: 'Svelte',
    title: 'Svelte todo list app',
    description: 'Sveltejs todo with TailwindCSS and Snowpack',
    url: 'https://github.com/briven/briven/tree/master/examples/todo-list/sveltejs-todo-list',
    type: 'app',
  },
  {
    framework: 'Flutter',
    title: 'Flutter chat app',
    description: 'A Flutter chat app built with briven-flutter',
    url: 'https://github.com/briven-community/flutter-chat',
    type: 'mobile',
  },
  {
    framework: 'Swift',
    title: 'Swift user management app',
    description: 'Swift user management app using briven-swift',
    url: 'https://github.com/briven/briven-swift/tree/main/Examples/UserManagement',
    type: 'mobile',
  },
  {
    framework: 'Swift',
    title: 'Swift Slack Clone',
    description: 'Swift Slack clone app using briven-swift',
    url: 'https://github.com/briven/briven-swift/tree/main/Examples/SlackClone',
    type: 'mobile',
  },
  {
    framework: 'Flutter',
    title: 'Flutter MFA app',
    description: 'A Flutter app demonstrating how to implement MFA',
    url: 'https://github.com/briven/briven/tree/master/examples/auth/flutter-mfa',
  },
  {
    framework: 'NuxtJS',
    title: 'NuxtJS todo list app',
    description: 'NuxtJS todo app example',
    url: 'https://github.com/nuxt-modules/briven/tree/main/demo',
  },
]
